apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- filebrowser/deployment.yaml
- filebrowser/media-pv.yaml
- filebrowser/media-pvc.yaml
- filebrowser/namespace.yaml
- filebrowser/service.yaml
- flux-system/gotk-components.yaml
- flux-system/gotk-sync.yaml
- headlamp/headlamb-token-secret.yaml
- headlamp/helmrelease.yaml
- headlamp/helmrepository.yaml
- headlamp/ingress.yaml
- headlamp/namespace.yaml
- homepage/clusterrole.yaml
- homepage/clusterrolebinding.yaml
- homepage/configmap.yaml
- homepage/deployment.yaml
- homepage/namespace.yaml
- homepage/secret.yaml
- homepage/service.yaml
- homepage/serviceaccount.yaml
- immich/helmrelease.yaml
- immich/helmrepository.yaml
- immich/immich-db-secret.sops.yaml
- immich/library-pv-local.yaml
- immich/library-pvc-local.yaml
- immich/namespace.yaml
- immich/postgres-deployment.yaml
- immich/postgres-service.yaml
- immich/upload-pv-local.yaml
- immich/upload-pvc-local.yaml
- metallb-system/helmrelease.yaml
- metallb-system/helmrepo.yaml
- metallb-system/ipaddresspool.yaml
- metallb-system/l2advertisement.yaml
- monitoring/kube-prometheus-stack/helmrelease.yaml
- monitoring/kube-prometheus-stack/helmrepo.yaml
- monitoring/loki/alloy-helmrelease.yaml
- monitoring/loki/helmrepository.yaml
- monitoring/loki/loki-helmrelease.yaml
- monitoring/namespace.yaml
- nvidia-device-plugin/helmrelease.yaml
- nvidia-device-plugin/helmrepository.yaml
- nvidia-device-plugin/namespace.yaml
- nvidia-device-plugin/runtimeclass.yaml
- pihole/helmrelease.yaml
- pihole/helmrepo.yaml
- pihole/namespace.yaml
- streaming/flaresolverr/deployment.yaml
- streaming/flaresolverr/service.yaml
- streaming/jellyfin/deployment.yaml
- streaming/jellyfin/media-pv.yaml
- streaming/jellyfin/media-pvc.yaml
- streaming/jellyfin/service.yaml
- streaming/namespace.yaml
- streaming/prowlarr/deployment.yaml
- streaming/prowlarr/service.yaml
- streaming/qbittorrent/deployment.yaml
- streaming/qbittorrent/qbittorrent-vpn-wg-secret.sops.yaml
- streaming/qbittorrent/service.yaml
- streaming/qbittorrent-direct/deployment.yaml
- streaming/qbittorrent-direct/service.yaml
- streaming/qui/deployment.yaml
- streaming/qui/service.yaml
- streaming/radarr/deployment.yaml
- streaming/radarr/service.yaml
- streaming/seer/helmrelease.yaml
- streaming/seer/helmrepository.yaml
- streaming/sonarr/deployment.yaml
- streaming/sonarr/service.yaml
- traefik-helmchartconfig.yaml
