apiVersion: ENC[AES256_GCM,data:4bs=,iv:oPPhS3QKDLm635SFvnkHx/N861pThqMTkw1oCwCNg7U=,tag:5GuVxIo08iZP4VBNvx6xkg==,type:str]
kind: ENC[AES256_GCM,data:p9ItomgN,iv:PVfRlIETaenAhFSlRnmMJQ9ywwcH0NxXgXYDBCG/tQ8=,tag:BT75zc4/giJScDBjpb4PAA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VkPDuY49DTh1pJ7HJ/oCSg==,iv:iy9UasF2ENpSGbvZbwX7dV89Ex9pkhwLIICcBVxjb8Q=,tag:i72dlg4VenR2Xbbtbtn8xA==,type:str]
    namespace: ENC[AES256_GCM,data:3dmiBdmx,iv:JTMYxD1o6WAJMLO30oh1x6jiV6fnKCnjt7Id7oaWfCQ=,tag:bwC1e08wm5x8tUNTwruTUw==,type:str]
type: ENC[AES256_GCM,data:SIzhVwVV,iv:Kssf+BINqhFvfwm0d6y9G4aCZLOUaHB4vAko9gbHqPI=,tag:XDARbuL6OS/StwztPig6tw==,type:str]
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:aywr21sothF0fTQSiGc=,iv:fLibLs2eAYiQShua5rZxLaeMci5UrADqHk+BJ2UJHgM=,tag:fwOD9ptqghzUMF5B2wdj5w==,type:str]
    DB_URL: ENC[AES256_GCM,data:q4SpbHlmBBsb0FqOoz9YOYz5akX7jpSJlnTdEPBfg4eZrfG1ce8UZhZNbphE6TPK/GiiAS7KJLZOgTk1zVY=,iv:WkvaTLgak3GFrF5+va6PTMGq74Hp2mtQbNT0wuFb1XI=,tag:QtZpeh7a0eyJILQQcrDdyA==,type:str]
sops:
    age:
        - recipient: age1lh9d945vv33slydy9kavezqh34jsqapa3prdvm82twqnem3uxcfq724qwd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodEs0MG9DaEk4SkduSG1M
            d01EbGphM2ZFN2lxUFhGcmJkVWNxTVNKK1JRClZzY2N3QWh0d016SDFYc256Z01L
            MDZHSkJhRjd6SnpZaGk1NGJLMWxOYVkKLS0tIGxQbVdUTU0rZmlqYlRrRkJJVVRy
            NXRTTUg2Y0wrM21zcTU2NE1NM2loU1UKGP9mkVU65JqmYXIb0Sxi4Oj1Mr/ZEV3r
            qSLStGATcDOg9Sq9Kp/D6Xso2ufaE+gkeHnK5TEoyrB3vpzNCKzJMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T00:59:50Z"
    mac: ENC[AES256_GCM,data:XTPbQ2uKyZluRKw3czLpxxSCrnKO7TVN9Qj2NZmIh6dubUNpUSJv22LyUuO5WQJ5Im6qsKdkpAHKxWHJokAF8/f7oS/Tk0i9BgaC+FJohzbl8O4P9DMbaTsO0AWocDQhkx0t+qAC/aX9ugVdQXA547h3bq8gQ6EQ0RqrLHHe/K8=,iv:snEOLK9kAVjLusFBOraFpMQjTkNG6vyVi6EBE3CqBk8=,tag:e78nFQZ3RC5O0gnzewEZeQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
