apiVersion: v1
kind: Service
metadata:
  name: immich-postgres
  namespace: immich
spec:
  type: ClusterIP
  selector:
    app: immich-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: postgres
