apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: 2.34.0   # vérifie la dernière version
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system

  values:
    replicaCount: 1

    serviceDNS:
      type: LoadBalancer
      loadBalancerIP: 192.168.0.200
      annotations: {}

    serviceWeb:
      type: LoadBalancer
      loadBalancerIP: 192.168.0.201
      annotations: {}

    adminPassword: "admin"

    persistentVolumeClaim:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 1Gi

