apiVersion: v1
kind: Service
metadata:
  name: drawio
  namespace: drawio
  labels:
    app.kubernetes.io/name: drawio
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.42.97
  selector:
    app.kubernetes.io/name: drawio
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
