apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: streaming
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 2Ti
  volumeName: jellyfin-media-nfs
