apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: nvidia-device-plugin
spec:
  interval: 15m
  chart:
    spec:
      chart: nvidia-device-plugin
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: flux-system
      interval: 1h
  values:
    runtimeclass: nvidia
    nodeSelector:
      nvidia.com/gpu.present: "true"
    tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "transcoding"
        effect: "NoSchedule"
