apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 30m
  chart:
    spec:
      chart: headlamp
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
      interval: 1h
  values:
    config:
      inCluster: true
      baseURL: "/"

    service:
      type: LoadBalancer

    serviceAccount:
      create: true
    
    clusterRoleBinding:
      create: true
      clusterRoleName: cluster-admin

