apiVersion: ENC[AES256_GCM,data:l9I=,iv:uFvBFDLgduj04knonwsKF8xlddqiIJtgZTDF+pL9S9U=,tag:TqYxyoZPt37G/SFjCAiK8Q==,type:str]
kind: ENC[AES256_GCM,data:pT3vEphT,iv:LLXfEVH1/7XPsO9cmeToWaMjvPBoSCSUSfEO6McSPuY=,tag:ti19cPI4tfhPMYJAeYkXbQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:h26PXS1QXwcryWOvBvMa6sbcSkdLUbY=,iv:SpTazJukY4d8fPKZJZgSYpNcbBeFFCuSDh9C8pGo5ag=,tag:G9NO5Y+0ZBT+Oh4/ERP6+A==,type:str]
    namespace: ENC[AES256_GCM,data:k2pLxj9HeZH+,iv:zuP3WLCM0E5QhhnTfbrqq/2kQrD2BU97T/Xcjqv+iX4=,tag:b1CKKeTqwyMo67p8ZGqZIA==,type:str]
type: ENC[AES256_GCM,data:lW0OLxCX,iv:8K7Y1bWJMWjxDG9FpaDqqqvVPH0XfA+zPXHV1I6f1RI=,tag:I5fZOOFf5D4sJWpdX3j6+A==,type:str]
stringData:
    #ENC[AES256_GCM,data:6TVMNbgN2oJs1cZgvw==,iv:kUjtMQ6EcLjIiumH8DG5Bv8XjLBYi1+YMjesny+OL74=,tag:oI8/CCSDbesZKYwQuoEnzQ==,type:comment]
    OPENVPN_USER: ENC[AES256_GCM,data:4cWNdsUWT2c=,iv:teVUOI2H3/wTG+qVUz6UHukwXo8y2Jb2bqRoPbvlvY0=,tag:OiWnAzIw84pm+YxNA3rs5A==,type:str]
    #ENC[AES256_GCM,data:PK7iL/u4V67iMpEEaSCFb5g5C2yRsjCYQw==,iv:hqpNlTa0pdHHN8P7Dg/NkXnpbG4So/NE+OX+67CUUOg=,tag:b0ZSQj6CMCGNSE3HXvnhmA==,type:comment]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:I9JuHZLxLGt2OA==,iv:Jzh6IPfia8XND54Q7ebIXtf1RrTPyrgUhBAuQtCyiP4=,tag:TlDpA2HNWiO9+rvA3HSTXA==,type:str]
sops:
    age:
        - recipient: age1lh9d945vv33slydy9kavezqh34jsqapa3prdvm82twqnem3uxcfq724qwd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIamUvR2JUS2YxRSs3VGh0
            L2pBbEpKc0NFeGI2eTVvd1kycmVUZUdyT1dZClg2Qk4xenlWODl1T1ZBaGhFRWVS
            TFlaUXpDTk90MmNmK0RSUGdFWFdHSWsKLS0tIDJNblVjMkJJMDR2RC9KMlN0d09S
            Wlhab0NRMjB3SWgraCtWYXBLNnFxancKWa9e1af93KYWTTKDbOZjQqvEuoNm4TmZ
            vB/mHXlEOsh6mheKAje1V28HAcIV4w4OWSMfyt8svpJ1+bpw3Ow58Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T04:50:24Z"
    mac: ENC[AES256_GCM,data:tHm0fGZOpWmNmHY8AXh1sEY7r/M0cEbnS/vJOUpuB51UyCnwByImGOQrP3liOrXyaojN7XAmBBYk7p5wS6ThttabxTzOi3/33Liww/TNH1YqAODtKg0gv85W1PzZJPQcjk/dWlWx1UjLXmxua0Xw4PtCoYnaPdHp0WiXCLJrOBQ=,iv:EZQbbdLDHDYPYQFrIVyWDbxP2eaK9Di3c19YzDNFwdE=,tag:h7rXJPQOamhqMrUt2zzPxQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
