apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 12h
  values:
    deploymentMode: SingleBinary

    loki:
      auth_enabled: false

    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 20Gi
        storageClass: local-path

    # optionnel mais utile
    monitoring:
      dashboards:
        enabled: true
      rules:
        enabled: true

